#ifndef CTXML__XML__HPP
#define CTXML__XML__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctxml {

struct xml {

	// NONTERMINALS:
	struct after_lt_content {};
	struct after_lt_epilog {};
	struct after_lt_prolog {};
	struct attribute_value {};
	struct attributes {};
	struct attributes_after_ws {};
	struct attval_dq_chars_push_text_char_anon {};
	struct attval_dq_more {};
	struct attval_sq_chars_push_text_char_anon {};
	struct attval_sq_more {};
	struct bang_content {};
	struct cdata_after_rb {};
	struct cdata_after_rbrb {};
	struct cdata_body {};
	struct char_reference {};
	struct comment_after_minus {};
	struct comment_body {};
	struct content {};
	struct dec_reference_tail {};
	struct document {}; using _start = document;
	struct element_after_name {};
	struct entity {};
	struct entity_a {};
	struct epilog {};
	struct epilog_more {};
	struct hex_reference_tail {};
	struct misc {};
	struct name_tail {};
	struct pi_after_quest {};
	struct pi_body {};

	// 'action' types:
	struct attribute_name: ctll::action {};
	struct begin_dec: ctll::action {};
	struct begin_hex: ctll::action {};
	struct begin_name: ctll::action {};
	struct cdata_bracket: ctll::action {};
	struct cdata_bracket_and_char: ctll::action {};
	struct cdata_brackets_and_char: ctll::action {};
	struct end_char_reference: ctll::action {};
	struct end_element: ctll::action {};
	struct entity_amp: ctll::action {};
	struct entity_apos: ctll::action {};
	struct entity_gt: ctll::action {};
	struct entity_lt: ctll::action {};
	struct entity_quot: ctll::action {};
	struct finish_open_tag: ctll::action {};
	struct finish_self_closing: ctll::action {};
	struct make_attribute: ctll::action {};
	struct open_element: ctll::action {};
	struct push_dec: ctll::action {};
	struct push_hex: ctll::action {};
	struct push_name_char: ctll::action {};
	struct push_text_char: ctll::action {};

	// TERMINALS
	using lt = ctll::term<'<'>;
	using ws_char__angle_open = ctll::set<'\x09','\x0A','\x0D',' ','<'>;
	using minus = ctll::term<'-'>;
	using excl = ctll::term<'!'>;
	using quest = ctll::term<'?'>;
	using name_start_chars = ctll::neg_set<'\x00','\x01','\x02','\x03','\x04','\x05','\x06','\x07','\x08','\x09','\x0A','\x0B','\x0C','\x0D','\x0E','\x0F','\x10','\x11','\x12','\x13','\x14','\x15','\x16','\x17','\x18','\x19','\x1A','\x1B','\x1C','\x1D','\x1E','\x1F',' ','!','\"','#','$','%','&','\'','\x28','\x29','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',';','<','=','>','?','@','[','\\',']','^','`','\x7B','|','\x7D','~','\x7F'>;
	using ws_char = ctll::set<'\x09','\x0A','\x0D',' '>;
	using set_1 = ctll::set<'\"','\'','/','<','=','>'>;
	using name_chars = ctll::neg_set<'\x00','\x01','\x02','\x03','\x04','\x05','\x06','\x07','\x08','\x09','\x0A','\x0B','\x0C','\x0D','\x0E','\x0F','\x10','\x11','\x12','\x13','\x14','\x15','\x16','\x17','\x18','\x19','\x1A','\x1B','\x1C','\x1D','\x1E','\x1F',' ','!','\"','#','$','%','&','\'','\x28','\x29','*','+',',','/',';','<','=','>','?','@','[','\\',']','^','`','\x7B','|','\x7D','~','\x7F'>;
	using ws_char__slash__equal_sign__angle_close = ctll::set<'\x09','\x0A','\x0D',' ','/','=','>'>;
	using ws_char__slash__angle_close = ctll::set<'\x09','\x0A','\x0D',' ','/','>'>;
	using gt = ctll::term<'>'>;
	using slash = ctll::term<'/'>;
	using eq = ctll::term<'='>;
	using quote = ctll::term<'\"'>;
	using squote = ctll::term<'\''>;
	using amp = ctll::term<'&'>;
	using text_chars = ctll::neg_set<'&','<'>;
	using C = ctll::term<'C'>;
	using D = ctll::term<'D'>;
	using A = ctll::term<'A'>;
	using T = ctll::term<'T'>;
	using lbracket = ctll::term<'['>;
	using t = ctll::term<'t'>;
	using semi = ctll::term<';'>;
	using u = ctll::term<'u'>;
	using o = ctll::term<'o'>;
	using l = ctll::term<'l'>;
	using g = ctll::term<'g'>;
	using a = ctll::term<'a'>;
	using q = ctll::term<'q'>;
	using hash = ctll::term<'#'>;
	using p = ctll::term<'p'>;
	using s = ctll::term<'s'>;
	using m = ctll::term<'m'>;
	using hexdig = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f'>;
	using x = ctll::term<'x'>;
	using digit = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using comment_chars = ctll::neg_set<'-'>;
	using cdata_chars = ctll::neg_set<']'>;
	using rbracket = ctll::term<']'>;
	using pi_chars = ctll::neg_set<'?'>;
	using attval_dq_chars = ctll::neg_set<'\"','&','<'>;
	using doublequote__ampersand = ctll::set<'\"','&'>;
	using attval_sq_chars = ctll::neg_set<'&','\'','<'>;
	using ampersand__quote = ctll::set<'&','\''>;

	// (q)LL1 function:
	static constexpr auto rule(document, ws_char__angle_open) -> ctll::push<misc, lt, after_lt_prolog>;

	static constexpr auto rule(after_lt_prolog, excl) -> ctll::push<ctll::anything, minus, minus, comment_body, misc, lt, after_lt_prolog>;
	static constexpr auto rule(after_lt_prolog, quest) -> ctll::push<ctll::anything, pi_body, misc, lt, after_lt_prolog>;
	static constexpr auto rule(after_lt_prolog, name_start_chars) -> ctll::push<ctll::anything, begin_name, push_name_char, name_tail, element_after_name, epilog>;

	static constexpr auto rule(epilog, ws_char__angle_open) -> ctll::push<misc, epilog_more>;
	static constexpr auto rule(epilog, ctll::epsilon) -> ctll::push<misc, epilog_more>;

	static constexpr auto rule(epilog_more, lt) -> ctll::push<ctll::anything, after_lt_epilog, epilog>;
	static constexpr auto rule(epilog_more, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(after_lt_epilog, excl) -> ctll::push<ctll::anything, minus, minus, comment_body>;
	static constexpr auto rule(after_lt_epilog, quest) -> ctll::push<ctll::anything, pi_body>;

	static constexpr auto rule(misc, ws_char) -> ctll::push<ctll::anything, misc>;
	static constexpr auto rule(misc, set_1) -> ctll::epsilon;
	static constexpr auto rule(misc, name_start_chars) -> ctll::epsilon;
	static constexpr auto rule(misc, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(name_tail, name_chars) -> ctll::push<ctll::anything, push_name_char, name_tail>;
	static constexpr auto rule(name_tail, ws_char__slash__equal_sign__angle_close) -> ctll::epsilon;

	static constexpr auto rule(element_after_name, ws_char__slash__angle_close) -> ctll::push<open_element, attributes>;

	static constexpr auto rule(attributes, slash) -> ctll::push<ctll::anything, gt, finish_self_closing>;
	static constexpr auto rule(attributes, gt) -> ctll::push<ctll::anything, finish_open_tag, content>;
	static constexpr auto rule(attributes, ws_char) -> ctll::push<ctll::anything, misc, attributes_after_ws>;

	static constexpr auto rule(attributes_after_ws, slash) -> ctll::push<ctll::anything, gt, finish_self_closing>;
	static constexpr auto rule(attributes_after_ws, gt) -> ctll::push<ctll::anything, finish_open_tag, content>;
	static constexpr auto rule(attributes_after_ws, name_start_chars) -> ctll::push<ctll::anything, begin_name, push_name_char, name_tail, attribute_name, misc, eq, misc, attribute_value, attributes>;

	static constexpr auto rule(attribute_value, quote) -> ctll::push<ctll::anything, attval_dq_chars_push_text_char_anon, attval_dq_more>;
	static constexpr auto rule(attribute_value, squote) -> ctll::push<ctll::anything, attval_sq_chars_push_text_char_anon, attval_sq_more>;

	static constexpr auto rule(attval_dq_more, quote) -> ctll::push<ctll::anything, make_attribute>;
	static constexpr auto rule(attval_dq_more, amp) -> ctll::push<ctll::anything, entity, attval_dq_chars_push_text_char_anon, attval_dq_more>;

	static constexpr auto rule(attval_sq_more, squote) -> ctll::push<ctll::anything, make_attribute>;
	static constexpr auto rule(attval_sq_more, amp) -> ctll::push<ctll::anything, entity, attval_sq_chars_push_text_char_anon, attval_sq_more>;

	static constexpr auto rule(content, text_chars) -> ctll::push<ctll::anything, push_text_char, content>;
	static constexpr auto rule(content, amp) -> ctll::push<ctll::anything, entity, content>;
	static constexpr auto rule(content, lt) -> ctll::push<ctll::anything, after_lt_content>;

	static constexpr auto rule(after_lt_content, slash) -> ctll::push<ctll::anything, name_start_chars, begin_name, push_name_char, name_tail, misc, gt, end_element>;
	static constexpr auto rule(after_lt_content, name_start_chars) -> ctll::push<ctll::anything, begin_name, push_name_char, name_tail, element_after_name, content>;
	static constexpr auto rule(after_lt_content, excl) -> ctll::push<ctll::anything, bang_content>;
	static constexpr auto rule(after_lt_content, quest) -> ctll::push<ctll::anything, pi_body, content>;

	static constexpr auto rule(bang_content, minus) -> ctll::push<ctll::anything, minus, comment_body, content>;
	static constexpr auto rule(bang_content, lbracket) -> ctll::push<ctll::anything, C, D, A, T, A, lbracket, cdata_body, content>;

	static constexpr auto rule(entity, l) -> ctll::push<ctll::anything, t, semi, entity_lt>;
	static constexpr auto rule(entity, g) -> ctll::push<ctll::anything, t, semi, entity_gt>;
	static constexpr auto rule(entity, a) -> ctll::push<ctll::anything, entity_a>;
	static constexpr auto rule(entity, q) -> ctll::push<ctll::anything, u, o, t, semi, entity_quot>;
	static constexpr auto rule(entity, hash) -> ctll::push<ctll::anything, char_reference>;

	static constexpr auto rule(entity_a, m) -> ctll::push<ctll::anything, p, semi, entity_amp>;
	static constexpr auto rule(entity_a, p) -> ctll::push<ctll::anything, o, s, semi, entity_apos>;

	static constexpr auto rule(char_reference, x) -> ctll::push<ctll::anything, hexdig, begin_hex, push_hex, hex_reference_tail>;
	static constexpr auto rule(char_reference, digit) -> ctll::push<ctll::anything, begin_dec, push_dec, dec_reference_tail>;

	static constexpr auto rule(hex_reference_tail, hexdig) -> ctll::push<ctll::anything, push_hex, hex_reference_tail>;
	static constexpr auto rule(hex_reference_tail, semi) -> ctll::push<ctll::anything, end_char_reference>;

	static constexpr auto rule(dec_reference_tail, digit) -> ctll::push<ctll::anything, push_dec, dec_reference_tail>;
	static constexpr auto rule(dec_reference_tail, semi) -> ctll::push<ctll::anything, end_char_reference>;

	static constexpr auto rule(comment_body, comment_chars) -> ctll::push<ctll::anything, comment_body>;
	static constexpr auto rule(comment_body, minus) -> ctll::push<ctll::anything, comment_after_minus>;

	static constexpr auto rule(comment_after_minus, minus) -> ctll::push<ctll::anything, gt>;
	static constexpr auto rule(comment_after_minus, comment_chars) -> ctll::push<ctll::anything, comment_body>;

	static constexpr auto rule(cdata_body, cdata_chars) -> ctll::push<ctll::anything, push_text_char, cdata_body>;
	static constexpr auto rule(cdata_body, rbracket) -> ctll::push<ctll::anything, cdata_after_rb>;

	static constexpr auto rule(cdata_after_rb, rbracket) -> ctll::push<ctll::anything, cdata_after_rbrb>;
	static constexpr auto rule(cdata_after_rb, cdata_chars) -> ctll::push<ctll::anything, cdata_bracket_and_char, cdata_body>;

	static constexpr auto rule(cdata_after_rbrb, gt) -> ctll::push<ctll::anything>;
	static constexpr auto rule(cdata_after_rbrb, rbracket) -> ctll::push<ctll::anything, cdata_bracket, cdata_after_rbrb>;
	static constexpr auto rule(cdata_after_rbrb, cdata_chars) -> ctll::push<ctll::anything, cdata_brackets_and_char, cdata_body>;

	static constexpr auto rule(pi_body, pi_chars) -> ctll::push<ctll::anything, pi_body>;
	static constexpr auto rule(pi_body, quest) -> ctll::push<ctll::anything, pi_after_quest>;

	static constexpr auto rule(pi_after_quest, gt) -> ctll::push<ctll::anything>;
	static constexpr auto rule(pi_after_quest, quest) -> ctll::push<ctll::anything, pi_after_quest>;
	static constexpr auto rule(pi_after_quest, pi_chars) -> ctll::push<ctll::anything, pi_body>;

	static constexpr auto rule(attval_dq_chars_push_text_char_anon, attval_dq_chars) -> ctll::push<ctll::anything, push_text_char, attval_dq_chars_push_text_char_anon>;
	static constexpr auto rule(attval_dq_chars_push_text_char_anon, doublequote__ampersand) -> ctll::epsilon;

	static constexpr auto rule(attval_sq_chars_push_text_char_anon, attval_sq_chars) -> ctll::push<ctll::anything, push_text_char, attval_sq_chars_push_text_char_anon>;
	static constexpr auto rule(attval_sq_chars_push_text_char_anon, ampersand__quote) -> ctll::epsilon;

};

}

#endif //CTXML__XML__HPP
